services:
  - type: web
    name: fintrack
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: NVIDIA_API_KEY
        sync: false
      - key: CLIENT_URL
        value: https://fintrack-v8ls.onrender.com
